server {
  listen 8000;
  server_name _;

  location = /rest/v1 {
    proxy_pass http://rest:3000/;
  }

  location /rest/v1/ {
    proxy_pass http://rest:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    return 404;
  }
}
