create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 280),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

do $$
begin
  create role anon nologin;
exception
  when duplicate_object then null;
end
$$;

grant usage on schema public to anon;
grant select, insert, update, delete on public.messages to anon;
grant usage, select on sequence public.messages_id_seq to anon;

drop policy if exists "Public can read messages" on public.messages;
create policy "Public can read messages" on public.messages
  for select to anon using (true);

drop policy if exists "Public can add messages" on public.messages;
create policy "Public can add messages" on public.messages
  for insert to anon with check (true);

drop policy if exists "Public can update messages" on public.messages;
create policy "Public can update messages" on public.messages
  for update to anon using (true) with check (true);

drop policy if exists "Public can delete messages" on public.messages;
create policy "Public can delete messages" on public.messages
  for delete to anon using (true);
