create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 280),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

create policy "Public can read messages"
  on public.messages for select
  to anon
  using (true);

create policy "Public can add messages"
  on public.messages for insert
  to anon
  with check (true);
